name: Reusable workflow to deploy
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: Name of the artifact
        required: false
        default: dist-files
        type: string
    secrets:
      my-secrets:
        required: true
    outputs:
      result:
        description: The result of deploy job
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Listing of files
        run: ls
      - name: Output Information
        run: echo "App is deployed..."
      - name: Print secrets
        run: echo ${{ secrets.my-secrets }}
      - name: Set deploy job output to result
        run: echo "step-result='deploy is success'" >> $GITHUB_OUTPUT
        # run: find dist/assets/*.js -type f -execdir echo 'script-js-file-name={}' >> $GITHUB_OUTPUT ';'
