name: Reusable workflow to deploy
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: Name of the artifact
        required: false
        default: dist-files
        type: string
    secrets:
      my-secrets:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Listing of files
        run: ls
      - name: Output Information
        run: echo "App is deployed..."
      - name: Print secrets
        run: echo ${{ secrets.my-secrets }}
